### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by vibhsaxena** [vibhsaxena/SEBC#1]

**Comment by vibhsaxena** [comment]
finished till the mysql replication. will start with the CM tomorrow.

**Comment by mfernest** [comment]
It's not necessary to mark your own lab as 'Incomplete'. If it is labelled Started but not Finished, I will assume the lab is still in progress.

**Comment by mfernest** [comment]
Please review your list of hostnames in `0_nodeIPs.md`. Submitting work like this suggests you don't know what you're doing.
`1_prechecks.md` - good
`2_replica_working.md` - a reason for putting the entire output to file is you then have a record of all the fields in a properly working installation. That's a good reference point to have for a validation check. No reason to skimp or crop on text output.
Missing screenshot of CM home page showing a healthy CDH cluster

INC
